entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "bentoluizv@gmail.com"
      storage: "/acme/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" # Para testes locais, usamos o servidor de staging do Let's Encrypt
      httpChallenge:
        entryPoint: web

api:
  insecure: true
  dashboard: true
