name: Terraform User Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            config.py
        sparse-checkout-cone-mode: false

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: chmod +x config.py
      - run: python config.py